server:
  port: 8989

spring:
  application:
    name: wms
  profiles:
    active: local
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
